name: test-fly-io-deploy
on: [push]
env:
  FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - use: action/checkout@v2
      - use: superfly/flyctl-action/setup-flyctl@master
      - use: flyctl deploy --remote-only
